# Generated by Django 2.1.3 on 2019-12-17 11:13

import channels_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_state', models.CharField(default='MAX', max_length=10)),
                ('room_name', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_key', models.CharField(max_length=255)),
                ('is_single', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chat_room',
                'verbose_name_plural': '채팅 방 목록',
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_exit', models.BooleanField(default=False)),
                ('last_read_date', models.DateTimeField(auto_now_add=True)),
                ('online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to='channels_app.ChatRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat_user',
                'verbose_name_plural': '채팅 유저 목록',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('type', models.CharField(default='message', max_length=10)),
                ('content', models.TextField(validators=[channels_app.models.validate_message_content])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='channels_app.ChatRoom')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': '메세지 목록',
            },
        ),
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_id ', models.CharField(max_length=32)),
                ('content', models.TextField(validators=[channels_app.models.validate_message_content])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chat_summary',
                'verbose_name_plural': '채팅 요약본',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatuser',
            unique_together={('user', 'chat_room')},
        ),
        
    ]
